In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

X = df.drop('species', axis = 1)
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)
model_knn.score(X_test, y_test)

1.0

In [7]:
from sklearn.svm import SVC

model_svm = SVC(gamma = 'auto', C=30, kernel='linear')
model_svm.fit(X_train, y_train)
model_svm.score(X_test, y_test)

1.0

# Grid Search CV

In [8]:
from sklearn.model_selection import GridSearchCV

classifier = GridSearchCV((model_svm), {
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear']
}, cv = 5, return_train_score = False)

classifier.fit(X, y)
classifier.cv_results_

{'mean_fit_time': array([0.00254307, 0.00221219, 0.00364289, 0.00174837, 0.00182185,
        0.00240636, 0.00209203, 0.00174208]),
 'std_fit_time': array([7.07045475e-04, 7.15771689e-04, 2.84145904e-03, 3.35516531e-05,
        4.65251362e-05, 9.81738265e-04, 1.98318896e-04, 6.93548787e-05]),
 'mean_score_time': array([0.00160742, 0.00150418, 0.00147052, 0.00130615, 0.00138865,
        0.00172062, 0.00156741, 0.00129981]),
 'std_score_time': array([1.55876091e-04, 2.45328153e-04, 9.73725996e-05, 3.93148116e-05,
        4.06436481e-05, 6.63614025e-04, 1.47432035e-04, 4.96122425e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [9]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002543,0.000707,0.001607,0.000156,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002212,0.000716,0.001504,0.000245,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003643,0.002841,0.001471,0.000097,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.001748,0.000034,0.001306,0.000039,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.001822,0.000047,0.001389,0.000041,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002406,0.000982,0.001721,0.000664,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002092,0.000198,0.001567,0.000147,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.001742,0.000069,0.001300,0.000050,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [10]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [11]:
classifier = GridSearchCV((model_knn), {
    'n_neighbors' : [1,5,10,20],
    'weights' : ['uniform','distance'],
    'p' : [1,2]
}, cv = 5, return_train_score = False)

classifier.fit(X,y)
classifier.cv_results_

{'mean_fit_time': array([0.00269966, 0.00177608, 0.00193801, 0.00171299, 0.00175195,
        0.00169616, 0.00171218, 0.00178642, 0.00183668, 0.00153856,
        0.00156708, 0.00191293, 0.00175548, 0.00159459, 0.00196624,
        0.00147123]),
 'std_fit_time': array([6.27275891e-04, 2.77855758e-05, 3.57878076e-04, 7.37152925e-05,
        4.05158407e-05, 4.06186898e-05, 5.93905610e-05, 5.12329074e-05,
        1.83269966e-04, 3.13939967e-05, 7.60855511e-05, 4.52828366e-04,
        1.96020210e-04, 3.48102230e-05, 7.18708304e-04, 3.88343981e-05]),
 'mean_score_time': array([0.00356178, 0.00198383, 0.00263195, 0.00192561, 0.00262733,
        0.0019042 , 0.00251203, 0.00195508, 0.00269222, 0.00176597,
        0.0023211 , 0.00195212, 0.0026794 , 0.00183439, 0.0026978 ,
        0.00178962]),
 'std_score_time': array([5.72042391e-04, 8.97588671e-05, 8.53673562e-05, 3.93593187e-05,
        1.82266187e-04, 4.19726141e-05, 3.90335414e-05, 2.88970400e-05,
        2.28537907e-04, 5.22259693e-05, 1.41645648e-04, 1.46723065e-04,
        2.38136143e-04, 4.44255134e-05, 3.73537826e-04, 1.32232747e-04]),
 'param_n_neighbors': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_p': masked_array(data=[1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_neighbors': 1, 'p': 1, 'weights': 'uniform'},
  {'n_neighbors': 1, 'p': 1, 'weights': 'distance'},
  {'n_neighbors': 1, 'p': 2, 'weights': 'uniform'},
  {'n_neighbors': 1, 'p': 2, 'weights': 'distance'},
  {'n_neighbors': 5, 'p': 1, 'weights': 'uniform'},
  {'n_neighbors': 5, 'p': 1, 'weights': 'distance'},
  {'n_neighbors': 5, 'p': 2, 'weights': 'uniform'},
  {'n_neighbors': 5, 'p': 2, 'weights': 'distance'},
  {'n_neighbors': 10, 'p': 1, 'weights': 'uniform'},
  {'n_neighbors': 10, 'p': 1, 'weights': 'distance'},
  {'n_neighbors': 10, 'p': 2, 'weights': 'uniform'},
  {'n_neighbors': 10, 'p': 2, 'weights': 'distance'},
  {'n_neighbors': 20, 'p': 1, 'weights': 'uniform'},
  {'n_neighbors': 20, 'p': 1, 'weights': 'distance'},
  {'n_neighbors': 20, 'p': 2, 'weights': 'uniform'},
  {'n_neighbors': 20, 'p': 2, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.93333333,
        0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.9       ,
        0.9       , 0.93333333, 0.9       , 0.96666667, 0.93333333,
        1.        , 1.        , 0.96666667, 0.93333333, 0.93333333,
        0.93333333]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.96      , 0.96      , 0.96      , 0.96      ,
        0.96      , 0.97333333, 0.96666667, 0.97333333, 0.97333333,
        0.98      , 0.98666667, 0.97333333, 0.97333333, 0.96      ,
        0.97333333]),
 'std_test_score': array([0.02494438, 0.02494438, 0.02494438, 0.02494438, 0.03265986,
        0.03265986, 0.02494438, 0.03651484, 0.02494438, 0.02494438,
        0.02666667, 0.01632993, 0.02494438, 0.02494438, 0.03265986,
        0.02494438]),
 'rank_test_score': array([12, 12, 12, 12, 10, 10,  3,  9,  3,  3,  2,  1,  3,  3, 12,  3],
       dtype=int32)}

In [12]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002700,0.000627,0.003562,0.000572,1,1,uniform,"{'n_neighbors': 1, 'p': 1, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,12
1,0.001776,0.000028,0.001984,0.000090,1,1,distance,"{'n_neighbors': 1, 'p': 1, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,12
2,0.001938,0.000358,0.002632,0.000085,1,2,uniform,"{'n_neighbors': 1, 'p': 2, 'weights': 'uniform'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,12
3,0.001713,0.000074,0.001926,0.000039,1,2,distance,"{'n_neighbors': 1, 'p': 2, 'weights': 'distance'}",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,12
4,0.001752,0.000041,0.002627,0.000182,5,1,uniform,"{'n_neighbors': 5, 'p': 1, 'weights': 'uniform'}",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,10
5,0.001696,0.000041,0.001904,0.000042,5,1,distance,"{'n_neighbors': 5, 'p': 1, 'weights': 'distance'}",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,10
6,0.001712,0.000059,0.002512,0.000039,5,2,uniform,"{'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
7,0.001786,0.000051,0.001955,0.000029,5,2,distance,"{'n_neighbors': 5, 'p': 2, 'weights': 'distance'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,9
8,0.001837,0.000183,0.002692,0.000229,10,1,uniform,"{'n_neighbors': 10, 'p': 1, 'weights': 'uniform'}",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
9,0.001539,0.000031,0.001766,0.000052,10,1,distance,"{'n_neighbors': 10, 'p': 1, 'weights': 'distan...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
10,0.001567,0.000076,0.002321,0.000142,10,2,uniform,"{'n_neighbors': 10, 'p': 2, 'weights': 'uniform'}",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,2
11,0.001913,0.000453,0.001952,0.000147,10,2,distance,"{'n_neighbors': 10, 'p': 2, 'weights': 'distan...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
12,0.001755,0.000196,0.002679,0.000238,20,1,uniform,"{'n_neighbors': 20, 'p': 1, 'weights': 'uniform'}",0.933333,1.000000,0.966667,0.966667,1.0,0.973333,0.024944,3
13,0.001595,0.000035,0.001834,0.000044,20,1,distance,"{'n_neighbors': 20, 'p': 1, 'weights': 'distan...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
14,0.001966,0.000719,0.002698,0.000374,20,2,uniform,"{'n_neighbors': 20, 'p': 2, 'weights': 'uniform'}",0.933333,1.000000,0.933333,0.933333,1.0,0.960000,0.032660,12
15,0.001471,0.000039,0.001790,0.000132,20,2,distance,"{'n_neighbors': 20, 'p': 2, 'weights': 'distan...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3

In [13]:
results[['param_n_neighbors', 'param_p', 'param_weights','mean_test_score']]

    param_n_neighbors  param_p param_weights  mean_test_score
0                   1        1       uniform         0.960000
1                   1        1      distance         0.960000
2                   1        2       uniform         0.960000
3                   1        2      distance         0.960000
4                   5        1       uniform         0.960000
5                   5        1      distance         0.960000
6                   5        2       uniform         0.973333
7                   5        2      distance         0.966667
8                  10        1       uniform         0.973333
9                  10        1      distance         0.973333
10                 10        2       uniform         0.980000
11                 10        2      distance         0.986667
12                 20        1       uniform         0.973333
13                 20        1      distance         0.973333
14                 20        2       uniform         0.960000
15                 20        2      distance         0.973333

In [14]:
from sklearn.model_selection import RandomizedSearchCV

classifier_random = RandomizedSearchCV((model_svm), {
    'C' : [1,10,20,30],
    'kernel' : ['rbf', 'linear']
},n_iter = 4, cv = 5, return_train_score=False)

classifier_random.fit(X, y)
classifier_random.cv_results_

{'mean_fit_time': array([0.00189362, 0.00167379, 0.00191154, 0.00239024]),
 'std_fit_time': array([1.63320980e-04, 3.49305920e-05, 1.56850479e-04, 5.34147285e-04]),
 'mean_score_time': array([0.00136933, 0.00127015, 0.00151458, 0.00179114]),
 'std_score_time': array([6.75928403e-05, 1.44872201e-05, 1.83960327e-04, 4.04677641e-04]),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'rbf'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 20, 10, 1],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 30},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'rbf', 'C': 1}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.9       , 0.96666667, 0.96666667]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.96666667, 0.98      , 0.98      ]),
 'std_test_score': array([0.03887301, 0.0421637 , 0.01632993, 0.01632993]),
 'rank_test_score': array([4, 3, 1, 1], dtype=int32)}

In [15]:
results_random = pd.DataFrame(classifier_random.cv_results_)
results_random

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001894,0.000163,0.001369,0.000068,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4
1,0.001674,0.000035,0.001270,0.000014,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
2,0.001912,0.000157,0.001515,0.000184,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002390,0.000534,0.001791,0.000405,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [16]:
results_random[['param_kernel', 'param_C', 'mean_test_score']]

  param_kernel  param_C  mean_test_score
0          rbf       30         0.960000
1       linear       20         0.966667
2          rbf       10         0.980000
3          rbf        1         0.980000